name: CD_back Pipeline

on:
  workflow_run:
    workflows: ['ci_back']
    branches: [main]
    types: [completed]

env:
  PORT: 8000
  COMMIT_SHA: ${{ github.sha }}
  IMAGE_NAME: emailserver
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH connection
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

    - name: Deploy to EC2
      run: |
        ssh -o StrictHostKeyChecking=no -l ubuntu ec2-34-224-82-4.compute-1.amazonaws.com <<EOF
          docker stop $(docker ps -q --filter "name=emailserver" --filter "publish=8000")
          docker rm $(docker ps -a -q --filter "name=emailserver" --filter "publish=8000")
          docker run -d -p ${{ env.PORT }}:8000 ${{ env.IMAGE_NAME}}:${{ env.COMMIT_SHA}}
        EOF